### ISSUE TITLE
添加 template string 响应式语法

### ISSUE THREAD

**Issue by syfxlin** [syfxlin/ustyled#6]
https://github.com/syfxlin/ustyled/blob/465d497d88faccc7b9232136fee221eea88f746b/src/api/create-css.ts#L42-L52

```css
/* Example */
.test {
    width: [1, 2, 3];
    height: [1, 2, 3];
}
```

```typescript
const values = value.match(/^\s*\[\s*([^\]]+?)\s*\]\s*/);
const arr = values.split(/\s*,\s*/g);
```
